// TODO: standardise camelcase
// TODO: some of these values are not single properties like paddingX
// TODO: some of these values are not simple classname selectors like divideX

type Property = {
  prefix: string,
  scale: string,
  supportsNegativeValues?: boolean,
  composite?: boolean,
  relatedProperties?: string[],
  acceptedValueTypes? : string[], // it's for arbitrary values. only Properties that have a shared prefix would have this (except for box-shadow, because it has an unhandled value type)
}

type Properties = {
  [key: string]: Property
};


export const properties: Properties = {

  "aspect-ratio": { prefix: 'aspect', scale: 'aspectRatio' },
  "accent-color": { prefix: 'accent', scale: 'accentColor' },
  "align-self": { prefix: 'self', scale: 'alignSelf' },
  "animation": { prefix: 'animate', scale: 'animation', composite: true, relatedProperties: ["animation-name", "animation-duration", "animation-timing-function", "animation-delay", "animation-iteration-count", "animation-direction", "animation-fill-mode", "animation-play-state"] },
  
  "background-color": { prefix: 'bg', scale: 'colors', acceptedValueTypes: ["color"] },
  "background-image": { prefix: 'bg', scale: 'backgroundImage', acceptedValueTypes: ["image"] },
  "background-opacity": { prefix: 'bg-opacity', scale: 'backgroundOpacity' },
  "background-position": { prefix: 'bg', scale: 'backgroundPosition', acceptedValueTypes: ["position"] },
  "background-size": { prefix: 'bg', scale: 'backgroundSize', acceptedValueTypes: ["bg-size"] },
  
  "border-color": { prefix: 'border', scale: 'colors', composite: true, acceptedValueTypes: ["color"] , relatedProperties: ["border-top-color", "border-right-color", "border-bottom-color", "border-left-color"] },
  "border-top-color": { prefix: "border-t", scale: "colors", acceptedValueTypes: ["color"] },
  "border-right-color": { prefix: "border-r", scale: "colors", acceptedValueTypes: ["color"] },
  "border-bottom-color": { prefix: "border-b", scale: "colors", acceptedValueTypes: ["color"] },
  "border-left-color": { prefix: "border-l", scale: "colors", acceptedValueTypes: ["color"] },

  "border-opacity": { prefix: 'border-opacity', scale: 'borderOpacity' },

  "border-style": { prefix: 'border', scale: 'borderStyle' },

  "border-width": { prefix: 'border', scale: 'borderWidth', acceptedValueTypes: ["length", "percentage", "line-width"] },
  "border-top-width": { prefix: 'border-t', scale: 'borderWidth', acceptedValueTypes: ["length", "percentage", "line-width"] },
  "border-right-width": { prefix: 'border-r', scale: 'borderWidth', acceptedValueTypes: ["length", "percentage", "line-width"] },
  "border-bottom-width": { prefix: 'border-b', scale: 'borderWidth', acceptedValueTypes: ["length", "percentage", "line-width"] },
  "border-left-width": { prefix: 'border-l', scale: 'borderWidth', acceptedValueTypes: ["length", "percentage", "line-width"] },

  "border-radius": { prefix: 'rounded', scale: 'borderRadius',  composite: true, relatedProperties: ["border-top-left-radius", "border-top-right-radius", "border-bottom-right-radius", "border-bottom-left-radius"]},
  "border-radius-top-left": { prefix: 'rounded-tl', scale: 'borderRadius', },
  "border-radius-top-right": { prefix: 'rounded-tr', scale: 'borderRadius', },
  "border-radius-bottom-right": { prefix: 'rounded-br', scale: 'borderRadius', },
  "border-radius-bottom-left": { prefix: 'rounded-bl', scale: 'borderRadius', },
  "border-radius-top": {prefix: 'rounded-t', scale: 'borderRadius',  composite: true, relatedProperties: ["border-top-left-radius", "border-top-right-radius"]},
  "border-radius-right": {prefix: 'rounded-r', scale: 'borderRadius',  composite: true, relatedProperties: ["border-top-right-radius", "border-bottom-right-radius"]},
  "border-radius-bottom": {prefix: 'rounded-b', scale: 'borderRadius',  composite: true, relatedProperties: ["border-bottom-right-radius", "border-bottom-left-radius"]},
  "border-radius-left": {prefix: 'rounded-l', scale: 'borderRadius',  composite: true, relatedProperties: ["border-bottom-left-radius", "border-top-left-radius"]},
  "border-radius-startStart-endStart": {prefix: 'rounded-s', scale: 'borderRadius',  composite: true, relatedProperties: ["border-start-start-radius", "border-end-start-radius"]},
  "border-radius-startEnd-endEnd": {prefix: 'rounded-e', scale: 'borderRadius',  composite: true, relatedProperties: ["border-start-end-radius", "border-end-end-radius"]},
  "border-radius-start-start": {prefix: 'rounded-ss', scale: 'borderRadius', },
  "border-radius-start-end": {prefix: 'rounded-se', scale: 'borderRadius', },
  "border-radius-end-end": {prefix: 'rounded-ee', scale: 'borderRadius', },
  "border-radius-end-start": {prefix: 'rounded-es', scale: 'borderRadius', },

  "border-spacing": { prefix: 'border-spacing', scale: 'borderSpacing', composite: true, relatedProperties: ["border-spacing-x", "border-spacing-y"] },
  "border-spacing-x": { prefix: 'border-spacing-x', scale: 'borderSpacing' },
  "border-spacing-y": { prefix: 'border-spacing-y', scale: 'borderSpacing' },

  // box-shadow does not get an acceptedValueTypes property because it gets an special value ( we handle it in index file )
  "box-shadow": { prefix: 'shadow', scale: 'boxShadow' },
  "box-shadow-color": { prefix: 'shadow', scale: 'colors', acceptedValueTypes: ["color"] },

  "columns": { prefix: 'columns', scale: 'columns', composite: true, relatedProperties: ["column-width", "column-count"] },
  "cursor": { prefix: 'cursor', scale: 'cursor' },
  "caret-color": { prefix: 'caret', scale: 'caretColor' },

  "divide-color": { prefix: 'divide', scale: 'colors' },
  "divide-opacity": { prefix: 'divide-opacity', scale: 'divideOpacity' },
  "divide-x": { prefix: 'divide-x', scale: 'divideWidth' },
  "divide-y": { prefix: 'divide-y', scale: 'divideWidth' },
  "drop-shadow": { prefix: 'drop-shadow', scale: 'dropShadow' },


  // filters, todo: the properties here are just wrong
  "grayscale": { prefix: 'grayscale', scale: 'grayscale' },
  "hueRotate": { prefix: 'hueRotate', scale: 'hueRotate', supportsNegativeValues: true },
  "invert": { prefix: 'invert', scale: 'invert' },
  "saturate": { prefix: 'saturate', scale: 'saturate' },
  "sepia": { prefix: 'sepia', scale: 'sepia' },
  "contrast": { prefix: 'contrast', scale: 'contrast' },
  "brightness": { prefix: 'brightness', scale: 'brightness' },
  "blur": { prefix: 'blur', scale: 'blur' },
  "backdrop-blur": { prefix: 'backdrop-blur', scale: 'backdropBlur' },
  "backdrop-brightness": { prefix: 'backdrop-brightness', scale: 'backdropBrightness' },
  "backdrop-contrast": { prefix: 'backdrop-contrast', scale: 'backdropContrast' },
  "backdrop-grayscale": { prefix: 'backdrop-grayscale', scale: 'backdropGrayscale' },
  "backdrop-hue-rotate": { prefix: 'backdrop-hueRotate', scale: 'backdropHueRotate' },
  "backdrop-invert": { prefix: 'backdrop-invert', scale: 'backdropInvert' },
  "backdrop-opacity": { prefix: 'backdrop-opacity', scale: 'backdropOpacity' },
  "backdrop-saturate": { prefix: 'backdrop-saturate', scale: 'backdropSaturate' },
  "backdrop-sepia": { prefix: 'backdrop-sepia', scale: 'backdropSepia' },

  "fill": { prefix: 'fill', scale: 'colors' },
  
  "flex": { prefix: 'flex', scale: 'flex', composite: true, relatedProperties: ["flex-grow", "flex-shrink", "flex-basis"] },
  "flex-grow": { prefix: 'flex-grow', scale: 'flexGrow' },
  "flex-shrink": { prefix: 'flex-shrink', scale: 'flexShrink' },

  "flex-basis": { prefix: 'basis', scale: 'flexBasis' },
  "font-weight": { prefix: 'font', scale: 'fontWeight', acceptedValueTypes: ["number"] },
  "font-family": { prefix: 'font', scale: 'fontFamily', acceptedValueTypes: ["generic-name", "family-name"] },
  "font-size": { prefix: 'text', scale: 'fontSize', acceptedValueTypes: ["length", "percentage"] },

  "gap": { prefix: 'gap', scale: 'gap', composite: true, relatedProperties: ["row-gap", "column-gap"] },
  "row-gap": { prefix: 'gap-x', scale: 'gap' },
  "column-gap": { prefix: 'gap-y', scale: 'gap' },

  "grid-auto-columns": { prefix: 'auto-cols', scale: 'gridAutoColumns' },
  "grid-auto-rows": { prefix: 'auto-rows', scale: 'gridAutoRows' },
  "grid-column": { prefix: 'col', scale: 'gridColumn', composite: true, relatedProperties: ["grid-column-start", "grid-column-end"] },
  "grid-column-end": { prefix: 'col-end', scale: 'gridColumnEnd' },
  "grid-column-start": { prefix: 'col-start', scale: 'gridColumnStart' },
  "grid-row": { prefix: 'row', scale: 'gridRow', composite: true, relatedProperties: ["grid-row-start", "grid-row-end"] },
  "grid-row-end": { prefix: 'row-end', scale: 'gridRowEnd' },
  "grid-row-start": { prefix: 'row-start', scale: 'gridRowStart' },
  "grid-template-columns": { prefix: 'grid-cols', scale: 'gridTemplateColumns' },
  "grid-template-rows": { prefix: 'grid-rows', scale: 'gridTemplateRows' },
  
  // gradientColorStops
  "gradient-from": { prefix: 'from', scale: 'colors' },
  "gradient-via": { prefix: 'via', scale: 'colors' },
  "gradient-to": { prefix: 'to', scale: 'colors' },

  "height": { prefix: 'h', scale: 'height' },

  "inset": { prefix: 'inset', scale: 'inset', supportsNegativeValues: true , composite: true, relatedProperties: ["top", "right", "bottom", "left"]},
  "inset-x": { prefix: 'inset-x', scale: 'inset', supportsNegativeValues: true, composite: true, relatedProperties: ["right", "left"]},
  "inset-y": { prefix: 'inset-y', scale: 'inset', supportsNegativeValues: true, composite: true, relatedProperties: ["top", "bottom"] },
  "top": { prefix: 'top', scale: 'inset', supportsNegativeValues: true },
  "right": { prefix: 'right', scale: 'inset', supportsNegativeValues: true },
  "bottom": { prefix: 'bottom', scale: 'inset', supportsNegativeValues: true },
  "left": { prefix: 'left', scale: 'inset', supportsNegativeValues: true },

  "letter-spacing": {
    prefix: 'tracking',
    scale: 'letterSpacing',
    supportsNegativeValues: false // set explicitly because it contains non-number values
  },
  "line-height": { prefix: 'leading', scale: 'lineHeight' },
  "list-style-type": { prefix: 'list', scale: 'listStyleType' },
  
  "margin": { prefix: 'm', scale: 'margin', supportsNegativeValues: true, composite: true, relatedProperties: ["margin-top", "margin-right", "margin-bottom", "margin-left"] },
  "margin-top": { prefix: 'mt', scale: 'margin', supportsNegativeValues: true },
  "margin-right": { prefix: 'mr', scale: 'margin', supportsNegativeValues: true },
  "margin-bottom": { prefix: 'mb', scale: 'margin', supportsNegativeValues: true },
  "margin-left": { prefix: 'ml', scale: 'margin', supportsNegativeValues: true },
  "margin-x": { prefix: 'mx', scale: 'margin', supportsNegativeValues: true, composite: true, relatedProperties: ["margin-right", "margin-left"]},
  "margin-y": { prefix: 'my', scale: 'margin', supportsNegativeValues: true, composite: true, relatedProperties: ["margin-top", "margin-bottom"]},

  "max-height": { prefix: 'max-h', scale: 'maxHeight' },
  "max-width": { prefix: 'max-w', scale: 'maxWidth' },
  "min-height": { prefix: 'min-h', scale: 'minHeight' },
  "min-width": { prefix: 'min-w', scale: 'minWidth' },
  
  "object-position": { prefix: 'object', scale: 'objectPosition' },
  "opacity": { prefix: 'opacity', scale: 'opacity' },
  "order": {
    prefix: 'order',
    scale: 'order',
    supportsNegativeValues: false // set explicitly because it contains non-number values
  },

  "outline-color": { prefix: 'outline', scale: 'colors', acceptedValueTypes: ["color"] },
  "outline-offset": {
    prefix: 'outline-offset',
    scale: 'outlineOffset',
    supportsNegativeValues: true,
  },
  "outline-width": { prefix: 'outline', scale: 'outlineWidth', acceptedValueTypes: ["length", "percentage", "line-width"]},

  "padding": { prefix: 'p', scale: 'padding', composite: true, relatedProperties: ["padding-top", "padding-right", "padding-bottom", "padding-left"] },
  "padding-top": { prefix: 'pt', scale: 'padding' },
  "padding-right": { prefix: 'pr', scale: 'padding' },
  "padding-bottom": { prefix: 'pb', scale: 'padding' },
  "padding-left": { prefix: 'pl', scale: 'padding' },
  "padding-x": { prefix: 'px', scale: 'padding', composite: true, relatedProperties: ["padding-right", "padding-left"] },
  "padding-y": { prefix: 'py', scale: 'padding', composite: true, relatedProperties: ["padding-top", "padding-bottom"] },

  "placeholder-color": { prefix: 'placeholder', scale: 'colors' },
  "placeholder-opacity": { prefix: 'placeholder-opacity', scale: 'placeholderOpacity' },

  "ring-color": { prefix: 'ring', scale: 'colors', acceptedValueTypes: ["color"] },
  "ring-offset-color": { prefix: 'ring-offset', scale: 'colors', acceptedValueTypes: ["color"] },
  "ring-offset-width": { prefix: 'ring-offset', scale: 'ringOffsetWidth', acceptedValueTypes: ["length", "percentage"] },
  "ring-opacity": { prefix: 'ring-opacity', scale: 'ringOpacity' },
  "ring-width": { prefix: 'ring', scale: 'ringWidth', acceptedValueTypes: ["length", "percentage"] },

  "rotate": { prefix: 'rotate', scale: 'rotate' },

  "stroke": { prefix: 'stroke', scale: 'colors', acceptedValueTypes: ["color"] },
  "stroke-width": { prefix: 'stroke', scale: 'strokeWidth', acceptedValueTypes: ["length", "percentage"] },

  "scale": { prefix: 'scale', scale: 'scale' },

  "scroll-margin": { prefix: 'scroll-m', scale: 'scrollMargin' , supportsNegativeValues: true, composite: true, relatedProperties: ["scroll-margin-top", "scroll-margin-right", "scroll-margin-bottom", "scroll-margin-left"]},
  "scroll-margin-top": { prefix: 'scroll-mt', scale: 'scrollMargin' , supportsNegativeValues: true},
  "scroll-margin-right": { prefix: 'scroll-mr', scale: 'scrollMargin' , supportsNegativeValues: true},
  "scroll-margin-bottom": { prefix: 'scroll-mb', scale: 'scrollMargin' , supportsNegativeValues: true},
  "scroll-margin-left": { prefix: 'scroll-ml', scale: 'scrollMargin' , supportsNegativeValues: true},
  "scroll-margin-x": { prefix: 'scroll-mx', scale: 'scrollMargin' , supportsNegativeValues: true, composite: true, relatedProperties: ["scroll-margin-right", "scroll-margin-left"]},
  "scroll-margin-y": { prefix: 'scroll-my', scale: 'scrollMargin' , supportsNegativeValues: true, composite: true, relatedProperties: ["scroll-margin-top", "scroll-margin-bottom"]},
  "scroll-margin-inline-start": { prefix: 'scroll-ms', scale: 'scrollMargin' , supportsNegativeValues: true},
  "scroll-margin-inline-end": { prefix: 'scroll-me', scale: 'scrollMargin' , supportsNegativeValues: true},

  "scroll-padding": { prefix: 'scroll-p', scale: 'scrollPadding', composite: true, relatedProperties: ["scroll-padding-top", "scroll-padding-right", "scroll-padding-bottom", "scroll-padding-left"]},
  "scroll-padding-top": { prefix: 'scroll-pt', scale: 'scrollPadding' },
  "scroll-padding-right": { prefix: 'scroll-pr', scale: 'scrollPadding' },
  "scroll-padding-bottom": { prefix: 'scroll-pb', scale: 'scrollPadding' },
  "scroll-padding-left": { prefix: 'scroll-pl', scale: 'scrollPadding' },
  "scroll-padding-x": { prefix: 'scroll-px', scale: 'scrollPadding', composite: true, relatedProperties: ["scroll-padding-right", "scroll-padding-left"]},
  "scroll-padding-y": { prefix: 'scroll-py', scale: 'scrollPadding', composite: true, relatedProperties: ["scroll-padding-top", "scroll-padding-bottom"]},
  "scroll-padding-inline-start": { prefix: 'scroll-ps', scale: 'scrollPadding'},
  "scroll-padding-inline-end": { prefix: 'scroll-pe', scale: 'scrollPadding'},

  "skew": { prefix: 'skew', scale: 'skew' },
  "space-x": { prefix: 'space-x', scale: 'space' },
  "space-y": { prefix: 'space-y', scale: 'space' },

  "color": { prefix: 'text', scale: 'colors', acceptedValueTypes: ["color"] },
  "text-decoration-color": { prefix: 'decoration', scale: 'textDecorationColor', acceptedValueTypes: ["color"] },
  "text-decoration-thickness": { prefix: 'decoration', scale: 'textDecorationThickness', acceptedValueTypes: ["length", "percentage", "line-width"] },
  "text-indent": {
    prefix: 'indent',
    scale: 'textIndent',
    supportsNegativeValues: true
  },
  "text-opacity": { prefix: 'text-opacity', scale: 'textOpacity' },
  "text-underline-offset": { prefix: 'underline-offset', scale: 'textUnderlineOffset' },

  "transform-origin": { prefix: 'origin', scale: 'transformOrigin' },
  
  "transition-delay": { prefix: 'delay', scale: 'transitionDelay' },
  "transition-duration": { prefix: 'duration', scale: 'transitionDuration' },
  "transition-timing-function": { prefix: 'ease', scale: 'transitionTimingFunction' },
  "transition-property": { prefix: 'transition', scale: 'transitionProperty' },
  
  "translate": { prefix: 'translate', scale: 'translate', supportsNegativeValues: true , composite: true, relatedProperties: ["translate-y", "translate-x"]},
  "translate-x": { prefix: 'translate-x', scale: 'translate', supportsNegativeValues: true },
  "translate-y": { prefix: 'translate-y', scale: 'translate', supportsNegativeValues: true },

  "width": { prefix: 'w', scale: 'width' },
  "will-change": { prefix: 'will-change', scale: 'willChange' },

  "z-index": { prefix: 'z', scale: 'zIndex', supportsNegativeValues: true },
};

// .sort((a, b) => b.prefix.length - a.prefix.length);
// TODO: we sort by lengh of prefix so that text-opacity- is matched before text-

export const namedClassProperties = {
  absolute: { position: 'absolute' },
  'align-baseline': { 'vertical-align': 'baseline' },
  'align-bottom': { 'vertical-align': 'bottom' },
  'align-middle': { 'vertical-align': 'middle' },
  'align-sub': { 'vertical-align': 'sub' },
  'align-super': { 'vertical-align': 'super' },
  'align-text-bottom': { 'vertical-align': 'text-bottom' },
  'align-text-top': { 'vertical-align': 'text-top' },
  'align-top': { 'vertical-align': 'top' },
  antialiased: {
    '-webkit-font-smoothing': 'antialiased',
    '-moz-osx-font-smoothing': 'grayscale'
  },
  'appearance-none': { appearance: 'none' },
  'backdrop-filter-none': { 'backdrop-filter': 'none' },
  'bg-blend-color': { 'background-blend-mode': 'color' },
  'bg-blend-color-burn': { 'background-blend-mode': 'color-burn' },
  'bg-blend-color-dodge': { 'background-blend-mode': 'color-dodge' },
  'bg-blend-darken': { 'background-blend-mode': 'darken' },
  'bg-blend-difference': { 'background-blend-mode': 'difference' },
  'bg-blend-exclusion': { 'background-blend-mode': 'exclusion' },
  'bg-blend-hard-light': { 'background-blend-mode': 'hard-light' },
  'bg-blend-hue': { 'background-blend-mode': 'hue' },
  'bg-blend-lighten': { 'background-blend-mode': 'lighten' },
  'bg-blend-luminosity': { 'background-blend-mode': 'luminosity' },
  'bg-blend-multiply': { 'background-blend-mode': 'multiply' },
  'bg-blend-normal': { 'background-blend-mode': 'normal' },
  'bg-blend-overlay': { 'background-blend-mode': 'overlay' },
  'bg-blend-saturation': { 'background-blend-mode': 'saturation' },
  'bg-blend-screen': { 'background-blend-mode': 'screen' },
  'bg-blend-soft-light': { 'background-blend-mode': 'soft-light' },
  'bg-clip-border': { 'background-clip': 'border-box' },
  'bg-clip-content': { 'background-clip': 'content-box' },
  'bg-clip-padding': { 'background-clip': 'padding-box' },
  'bg-clip-text': { 'background-clip': 'text' },
  'bg-fixed': { 'background-attachment': 'fixed' },
  'bg-local': { 'background-attachment': 'local' },
  'bg-no-repeat': { 'background-repeat': 'no-repeat' },
  'bg-origin-border': { 'background-origin': 'border-box' },
  'bg-origin-content': { 'background-origin': 'content-box' },
  'bg-origin-padding': { 'background-origin': 'padding-box' },
  'bg-repeat': { 'background-repeat': 'repeat' },
  'bg-repeat-round': { 'background-repeat': 'round' },
  'bg-repeat-space': { 'background-repeat': 'space' },
  'bg-repeat-x': { 'background-repeat': 'repeat-x' },
  'bg-repeat-y': { 'background-repeat': 'repeat-y' },
  'bg-scroll': { 'background-attachment': 'scroll' },
  block: { display: 'block' },
  'border-collapse': { 'border-collapse': 'collapse' },
  'border-dashed': { 'border-style': 'dashed' },
  'border-dotted': { 'border-style': 'dotted' },
  'border-double': { 'border-style': 'double' },
  'border-hidden': { 'border-style': 'hidden' },
  'border-none': { 'border-style': 'none' },
  'border-separate': { 'border-collapse': 'separate' },
  'border-solid': { 'border-style': 'solid' },
  'box-border': { 'box-sizing': 'border-box' },
  'box-content': { 'box-sizing': 'content-box' },
  'box-decoration-clone': { 'box-decoration-break': 'clone' },
  'box-decoration-slice': { 'box-decoration-break': 'slice' },
  'break-after-all': { 'break-after': 'all' },
  'break-after-auto': { 'break-after': 'auto' },
  'break-after-avoid': { 'break-after': 'avoid' },
  'break-after-avoid-page': { 'break-after': 'avoid-page' },
  'break-after-column': { 'break-after': 'column' },
  'break-after-left': { 'break-after': 'left' },
  'break-after-page': { 'break-after': 'page' },
  'break-after-right': { 'break-after': 'right' },
  'break-all': { 'word-break': 'break-all' },
  'break-before-all': { 'break-before': 'all' },
  'break-before-auto': { 'break-before': 'auto' },
  'break-before-avoid': { 'break-before': 'avoid' },
  'break-before-avoid-page': { 'break-before': 'avoid-page' },
  'break-before-column': { 'break-before': 'column' },
  'break-before-left': { 'break-before': 'left' },
  'break-before-page': { 'break-before': 'page' },
  'break-before-right': { 'break-before': 'right' },
  'break-inside-auto': { 'break-inside': 'auto' },
  'break-inside-avoid': { 'break-inside': 'avoid' },
  'break-inside-avoid-column': { 'break-inside': 'avoid-column' },
  'break-inside-avoid-page': { 'break-inside': 'avoid-page' },
  'break-keep': { 'word-break': 'keep-all' },
  'break-normal': { 'overflow-wrap': 'normal', 'word-break': 'normal' },
  'break-words': { 'overflow-wrap': 'break-word' },
  capitalize: { 'text-transform': 'capitalize' },
  'clear-both': { clear: 'both' },
  'clear-left': { clear: 'left' },
  'clear-none': { clear: 'none' },
  'clear-right': { clear: 'right' },
  collapse: { visibility: 'collapse' },
  'content-around': { 'align-content': 'space-around' },
  'content-baseline': { 'align-content': 'baseline' },
  'content-between': { 'align-content': 'space-between' },
  'content-center': { 'align-content': 'center' },
  'content-end': { 'align-content': 'flex-end' },
  'content-evenly': { 'align-content': 'space-evenly' },
  'content-start': { 'align-content': 'flex-start' },
  contents: { display: 'contents' },
  'content-none': { content: 'none' },
  'decoration-clone': { 'box-decoration-break': 'clone' },
  'decoration-slice': { 'box-decoration-break': 'slice' },
  'decoration-dashed': { 'text-decoration-style': 'dashed' },
  'decoration-dotted': { 'text-decoration-style': 'dotted' },
  'decoration-double': { 'text-decoration-style': 'double' },
  'decoration-solid': { 'text-decoration-style': 'solid' },
  'decoration-wavy': { 'text-decoration-style': 'wavy' },
  'diagonal-fractions': { 'font-variant-numeric': 'diagonal-fractions' },

  'divide-solid': { 'border-style': 'solid' },
  'divide-dashed': { 'border-style': 'dashed' },
  'divide-dotted': { 'border-style': 'dotted' },
  'divide-double': { 'border-style': 'double' },
  'divide-none': { 'border-style': 'none' },

  'filter-none': { filter: 'none' },
  fixed: { position: 'fixed' },
  flex: { display: 'flex' },
  'flex-col': { 'flex-direction': 'column' },
  'flex-col-reverse': { 'flex-direction': 'column-reverse' },
  'flex-nowrap': { 'flex-wrap': 'nowrap' },
  'flex-row': { 'flex-direction': 'row' },
  'flex-row-reverse': { 'flex-direction': 'row-reverse' },
  'flex-wrap': { 'flex-wrap': 'wrap' },
  'flex-wrap-reverse': { 'flex-wrap': 'wrap-reverse' },
  'float-left': { float: 'left' },
  'float-none': { float: 'none' },
  'float-right': { float: 'right' },
  'flow-root': { display: 'flow-root' },
  grid: { display: 'grid' },
  'grid-flow-col': { "grid-auto-flow": 'column' },
  'grid-flow-col-dense': { "grid-auto-flow": 'column dense' },
  'grid-flow-dense': { "grid-auto-flow": 'dense' },
  'grid-flow-row': { "grid-auto-flow": 'row' },
  'grid-flow-row-dense': { "grid-auto-flow": 'row dense' },
  hidden: { display: 'none' },
  inline: { display: 'inline' },
  'inline-block': { display: 'inline-block' },
  'inline-flex': { display: 'inline-flex' },
  'inline-grid': { display: 'inline-grid' },
  'inline-table': { display: 'inline-table' },
  invisible: { visibility: 'hidden' },
  isolate: { isolation: 'isolate' },
  'isolation-auto': { isolation: 'auto' },
  italic: { 'font-style': 'italic' },
  'items-baseline': { 'align-items': 'baseline' },
  'items-center': { 'align-items': 'center' },
  'items-end': { 'align-items': 'flex-end' },
  'items-start': { 'align-items': 'flex-start' },
  'items-stretch': { 'align-items': 'stretch' },
  'justify-around': { 'justify-content': 'space-around' },
  'justify-between': { 'justify-content': 'space-between' },
  'justify-center': { 'justify-content': 'center' },
  'justify-end': { 'justify-content': 'flex-end' },
  'justify-evenly': { 'justify-content': 'space-evenly' },
  'justify-items-center': { 'justify-items': 'center' },
  'justify-items-end': { 'justify-items': 'end' },
  'justify-items-start': { 'justify-items': 'start' },
  'justify-items-stretch': { 'justify-items': 'stretch' },
  'justify-self-auto': { 'justify-self': 'auto' },
  'justify-self-center': { 'justify-self': 'center' },
  'justify-self-end': { 'justify-self': 'end' },
  'justify-self-start': { 'justify-self': 'start' },
  'justify-self-stretch': { 'justify-self': 'stretch' },
  'justify-start': { 'justify-content': 'flex-start' },
  'line-through': { 'text-decoration-line': 'line-through' },
  'lining-nums': { 'font-variant-numeric': 'lining-nums' },
  'list-inside': { 'list-style-position': 'inside' },
  'list-item': { display: 'list-item' },
  'list-outside': { 'list-style-position': 'outside' },
  'list-image-none': {'list-style-image' : 'none'},
  lowercase: { 'text-transform': 'lowercase' },
  'mix-blend-color': { 'mix-blend-mode': 'color' },
  'mix-blend-color-burn': { 'mix-blend-mode': 'color-burn' },
  'mix-blend-color-dodge': { 'mix-blend-mode': 'color-dodge' },
  'mix-blend-darken': { 'mix-blend-mode': 'darken' },
  'mix-blend-difference': { 'mix-blend-mode': 'difference' },
  'mix-blend-exclusion': { 'mix-blend-mode': 'exclusion' },
  'mix-blend-hard-light': { 'mix-blend-mode': 'hard-light' },
  'mix-blend-hue': { 'mix-blend-mode': 'hue' },
  'mix-blend-lighten': { 'mix-blend-mode': 'lighten' },
  'mix-blend-luminosity': { 'mix-blend-mode': 'luminosity' },
  'mix-blend-multiply': { 'mix-blend-mode': 'multiply' },
  'mix-blend-normal': { 'mix-blend-mode': 'normal' },
  'mix-blend-overlay': { 'mix-blend-mode': 'overlay' },
  'mix-blend-plus-lighter': { 'mix-blend-mode': 'plus-lighter' },
  'mix-blend-saturation': { 'mix-blend-mode': 'saturation' },
  'mix-blend-screen': { 'mix-blend-mode': 'screen' },
  'mix-blend-soft-light': { 'mix-blend-mode': 'soft-light' },
  'no-underline': { 'text-decoration-line': 'none' },
  'normal-case': { 'text-transform': 'none' },
  'normal-nums': { 'font-variant-numeric': 'normal' },
  'not-italic': { 'font-style': 'normal' },
  'not-sr-only': {
    position: 'static',
    width: 'auto',
    height: 'auto',
    padding: '0',
    margin: '0',
    overflow: 'visible',
    clip: 'auto',
    "white-space": 'normal'
  },
  'object-contain': { 'object-fit': 'contain' },
  'object-cover': { 'object-fit': 'cover' },
  'object-fill': { 'object-fit': 'fill' },
  'object-none': { 'object-fit': 'none' },
  'object-scale-down': { 'object-fit': 'scale-down' },
  'oldstyle-nums': { 'font-variant-numeric': 'oldstyle-nums' },
  ordinal: { 'font-variant-numeric': 'ordinal' },
  outline: { 'outline-style': 'solid' },
  'outline-dashed': { 'outline-style': 'dashed' },
  'outline-dotted': { 'outline-style': 'dotted' },
  'outline-double': { 'outline-style': 'double' },
  'outline-none': { outline: '2px solid transparent', 'outline-offset': '2px' },
  'overflow-auto': { overflow: 'auto' },
  'overflow-clip': { overflow: 'clip' },
  'overflow-ellipsis': { 'text-overflow': 'ellipsis' },
  'overflow-hidden': { overflow: 'hidden' },
  'overflow-scroll': { overflow: 'scroll' },
  'overflow-visible': { overflow: 'visible' },
  'overflow-x-auto': { 'overflow-x': 'auto' },
  'overflow-x-clip': { 'overflow-x': 'clip' },
  'overflow-x-hidden': { 'overflow-x': 'hidden' },
  'overflow-x-scroll': { 'overflow-x': 'scroll' },
  'overflow-x-visible': { 'overflow-x': 'visible' },
  'overflow-y-auto': { 'overflow-y': 'auto' },
  'overflow-y-clip': { 'overflow-y': 'clip' },
  'overflow-y-hidden': { 'overflow-y': 'hidden' },
  'overflow-y-scroll': { 'overflow-y': 'scroll' },
  'overflow-y-visible': { 'overflow-y': 'visible' },
  overline: { 'text-decoration-line': 'overline' },
  'overscroll-auto': { 'overscroll-behavior': 'auto' },
  'overscroll-contain': { 'overscroll-behavior': 'contain' },
  'overscroll-none': { 'overscroll-behavior': 'none' },
  'overscroll-x-auto': { 'overscroll-behavior-x': 'auto' },
  'overscroll-x-contain': { 'overscroll-behavior-x': 'contain' },
  'overscroll-x-none': { 'overscroll-behavior-x': 'none' },
  'overscroll-y-auto': { 'overscroll-behavior-y': 'auto' },
  'overscroll-y-contain': { 'overscroll-behavior-y': 'contain' },
  'overscroll-y-none': { 'overscroll-behavior-y': 'none' },
  'place-content-around': { 'place-content': 'space-around' },
  'place-content-baseline': { 'place-content': 'baseline' },
  'place-content-between': { 'place-content': 'space-between' },
  'place-content-center': { 'place-content': 'center' },
  'place-content-end': { 'place-content': 'end' },
  'place-content-evenly': { 'place-content': 'space-evenly' },
  'place-content-start': { 'place-content': 'start' },
  'place-content-stretch': { 'place-content': 'stretch' },
  'place-items-baseline': { 'place-items': 'baseline' },
  'place-items-center': { 'place-items': 'center' },
  'place-items-end': { 'place-items': 'end' },
  'place-items-start': { 'place-items': 'start' },
  'place-items-stretch': { 'place-items': 'stretch' },
  'place-self-auto': { 'place-self': 'auto' },
  'place-self-center': { 'place-self': 'center' },
  'place-self-end': { 'place-self': 'end' },
  'place-self-start': { 'place-self': 'start' },
  'place-self-stretch': { 'place-self': 'stretch' },
  'pointer-events-auto': { 'pointer-events': 'auto' },
  'pointer-events-none': { 'pointer-events': 'none' },
  'proportional-nums': { 'font-variant-numeric': 'proportional-nums' },
  relative: { position: 'relative' },
  resize: { resize: 'both' },
  'resize-none': { resize: 'none' },
  'resize-x': { resize: 'horizontal' },
  'resize-y': { resize: 'vertical' },
  'ring-inset': { '--tw-ring-inset': 'inset' },
  'scroll-auto': { 'scroll-behavior': 'auto' },
  'scroll-smooth': { 'scroll-behavior': 'smooth' },
  'select-all': { 'user-select': 'all' },
  'select-auto': { 'user-select': 'auto' },
  'select-none': { 'user-select': 'none' },
  'select-text': { 'user-select': 'text' },
  'self-auto': { 'align-self': 'auto' },
  'self-baseline': { 'align-self': 'baseline' },
  'self-center': { 'align-self': 'center' },
  'self-end': { 'align-self': 'flex-end' },
  'self-start': { 'align-self': 'flex-start' },
  'self-stretch': { 'align-self': 'stretch' },
  'slashed-zero': { 'font-variant-numeric': 'slashed-zero' },

  'snap-align-none': { 'scroll-snap-align': 'none' },
  'snap-always': { 'scroll-snap-stop': 'always' },
  'snap-center': { 'scroll-snap-align': 'center' },
  'snap-end': { 'scroll-snap-align': 'end' },
  'snap-normal': { 'scroll-snap-stop': 'normal' },
  'snap-start': { 'scroll-snap-align': 'start' },

  '.snap-mandatory': { '--tw-scroll-snap-strictness': 'mandatory' },
  '.snap-proximity': { '--tw-scroll-snap-strictness': 'proximity' },

  '.snap-none': { 'scroll-snap-type': 'none' },
  '.snap-x': { 'scroll-snap-type': 'x var(--tw-scroll-snap-strictness)' },
  '.snap-y': { 'scroll-snap-type': 'y var(--tw-scroll-snap-strictness)' },
  '.snap-both': { 'scroll-snap-type': 'both var(--tw-scroll-snap-strictness)' },

  'sr-only': {
    position: 'absolute',
    width: '1px',
    height: '1px',
    padding: '0',
    margin: '-1px',
    overflow: 'hidden',
    clip: 'rect(0, 0, 0, 0)',
    "white-space": 'nowrap',
    borderWidth: '0'
  },
  'stacked-fractions': { 'font-variant-numeric': 'stacked-fractions' },
  static: { position: 'static' },
  sticky: { position: 'sticky' },
  'subpixel-antialiased': {
    '-webkit-font-smoothing': 'auto',
    '-moz-osx-font-smoothing': 'auto'
  },
  table: { display: 'table' },
  'table-auto': { 'table-layout': 'auto' },
  'table-caption': { display: 'table-caption' },
  'table-cell': { display: 'table-cell' },
  'table-column': { display: 'table-column' },
  'table-column-group': { display: 'table-column-group' },
  'table-fixed': { 'table-layout': 'fixed' },
  'table-footer-group': { display: 'table-footer-group' },
  'table-header-group': { display: 'table-header-group' },
  'table-row': { display: 'table-row' },
  'table-row-group': { display: 'table-row-group' },
  'tabular-nums': { 'font-variant-numeric': 'tabular-nums' },
  'text-center': { 'text-align': 'center' },
  'text-clip': { 'text-overflow': 'clip' },
  'text-ellipsis': { 'text-overflow': 'ellipsis' },
  'text-end': { 'text-align': 'end' },
  'text-justify': { 'text-align': 'justify' },
  'text-left': { 'text-align': 'left' },
  'text-right': { 'text-align': 'right' },
  'text-start': { 'text-align': 'start' },

  'touch-auto': { 'touch-action': 'auto' },
  'touch-none': { 'touch-action': 'none' },
  'touch-pan-x': { 'touch-action': 'pan-x' },
  'touch-pan-left': { 'touch-action': 'pan-left' },
  'touch-pan-right': { 'touch-action': 'pan-right' },
  'touch-pan-y': { 'touch-action': 'pan-y' },
  'touch-pan-up': { 'touch-action': 'pan-up' },
  'touch-pan-down': { 'touch-action': 'pan-down' },
  'touch-pinch-zoom': { 'touch-action': 'pinch-zoom' },
  'touch-manipulation': { 'touch-action': 'manipulation' },

  truncate: {
    overflow: 'hidden',
    'text-overflow': 'ellipsis',
    'white-space': 'nowrap'
  },
  underline: { 'text-decoration-line': 'underline' },
  uppercase: { 'text-transform': 'uppercase' },
  visible: { visibility: 'visible' },
  'whitespace-normal': { 'white-space': 'normal' },
  'whitespace-nowrap': { 'white-space': 'nowrap' },
  'whitespace-pre': { 'white-space': 'pre' },
  'whitespace-pre-line': { 'white-space': 'pre-line' },
  'whitespace-pre-wrap': { 'white-space': 'pre-wrap' }
};

type ArbitraryProperties = {
  [key: string]: {
    property : string,
    composite?: boolean,
    relatedProperties?: string[]
  }
}
export const arbitraryProperties : ArbitraryProperties = {
  "aspect-ratio" : { property: "aspect-ratio"},
  "appearance": {property: "appearance"},
  "accent-color": {property: "accent-color"},
  "all": {property: "all"},
  
  "animation": {property: "animation", composite: true, relatedProperties: ["animation-name", "animation-duration", "animation-timing-function", "animation-delay", "animation-iteration-count", "animation-direction", "animation-fill-mode", "animation-play-state"]},
  "animation-delay": {property: "animation-delay"},
  "animation-direction": {property: "animation-direction"},
  "animation-fill-mode": {property: "animation-fill-mode"},
  "animation-iteration-count": {property: "animation-iteration-count"},
  "animation-play-state": {property: "animation-play-state"},
  "animation-timing-function": {property: "animation-timing-function"},
  "animation-duration" : {property: 'animation-duration'},
  "animation-name" : {property: 'animation-name'},

  
  "align-content": {property: "align-content"},
  "align-items": {property: "align-items"},
  "align-self": {property: "align-self"},

  "backdrop-filter": {property: "backdrop-filter"},

  "backface-visibility": {property: "backface-visibility"},
  "-webkit-backface-visibility": {property: "-webkit-backface-visibility"},
  
  "background-image": { property: "background-image"},
  "background-position": { property: "background-position", composite: true, relatedProperties: ["background-position-x", "background-position-y"]},
  "background-position-x": { property: "background-position-x"},
  "background-position-y": { property: "background-position-y"},
  "background-size": { property: "background-size"},
  "background-blend-mode": { property: "background-blend-mode"},
  "background-clip": { property: "background-clip"},
  "background-color": {property: "background-color"},
  "background": {property: "background", composite: true, relatedProperties: ["background-color", "background-image", "background-position", "background-size", "background-repeat", "background-origin", "background-clip", "background-attachment"]},
  "background-attachment": {property: "background-attachment"},
  "background-repeat": {property: "background-repeat"},
  "background-origin": {property: "background-origin"},

  "border": {property: "border", composite: true, relatedProperties: ["border-width", "border-style", "border-color"]},
  "border-left": {property: "border-left", composite: true, relatedProperties: ["border-left-width", "border-left-style", "border-left-color"]},
  "border-right": {property: "border-right", composite: true, relatedProperties: ["border-right-width", "border-right-style", "border-right-color"]},
  "border-bottom": {property: "border-bottom", composite: true,relatedProperties: ["border-bottom-width", "border-bottom-style", "border-bottom-color"]},
  "border-top": {property: "border-top", composite: true,relatedProperties: ["border-top-width", "border-top-style", "border-left-color"]},

  "border-block": { property: "border-block", composite: true, relatedProperties: ["border-block-width", "border-block-style", "border-block-color"]},
  "border-block-color": { property: "border-block-color", composite: true, relatedProperties: ["border-block-start-color", "border-block-end-color"]},
  "border-block-end": { property: "border-block-end", composite: true, relatedProperties: ["border-block-end-width", "border-block-end-style", "border-block-end-color"]},
  "border-block-end-color": { property: "border-block-end-color"},
  "border-block-end-style": { property: "border-block-end-style"},
  "border-block-end-width": { property: "border-block-end-width"},
  "border-block-start": { property: "border-block-start", composite: true, relatedProperties: ["border-block-start-width", "border-block-start-style", "border-block-start-color"]},
  "border-block-start-color": { property: "border-block-start-color"},
  "border-block-start-style": { property: "border-block-start-style"},
  "border-block-start-width": { property: "border-block-start-width"},
  "border-block-style": { property: "border-block-style", composite: true, relatedProperties: ["border-block-start-style", "border-block-end-style"]},
  "border-block-width": { property: "border-block-width", composite: true, relatedProperties: ["border-block-start-width", "border-block-end-width"]},
  
  "border-color": {property: "border-color", composite: true, relatedProperties: ["border-top-color", "border-right-color", "border-bottom-color", "border-left-color"]},
  "border-top-color": {property: "border-top-color"},
  "border-right-color": {property: "border-right-color"},
  "border-bottom-color": {property: "border-bottom-color"},
  "border-left-color": {property: "border-left-color"},

  "border-style": {property: "border-style", composite: true, relatedProperties: ["border-top-style", "border-right-style", "border-bottom-style", "border-left-style"]},
  "border-top-style": {property: "border-top-style"},
  "border-right-style": {property: "border-right-style"},
  "border-bottom-style": {property: "border-bottom-style"},
  "border-left-style": {property: "border-left-style"},

  "border-width": {property: "border-width", composite: true, relatedProperties: ["border-top-width", "border-right-width", "border-bottom-width", "border-left-width"]},
  "border-top-width": {property: "border-top-width"},
  "border-right-width": {property: "border-right-width"},
  "border-bottom-width": {property: "border-bottom-width"},
  "border-left-width": {property: "border-left-width"},

  "border-radius": {property: "border-radius", composite: true, relatedProperties: ["border-top-left-radius", "border-top-right-radius", "border-bottom-right-radius", "border-bottom-left-radius"]},
  "border-top-left-radius": {property: "border-radius-top-left"},
  "border-top-right-radius": {property: "border-radius-top-right"},
  "border-bottom-left-radius": {property: "border-radius-bottom-left"},
  "border-bottom-right-radius": {property: "border-radius-bottom-right"},
  "border-start-start-radius": {property: "border-radius-start-start"},
  "border-start-end-radius": {property: "border-radius-start-end"},
  "border-end-end-radius": {property: "border-radius-end-end"},
  "border-end-start-radius": {property: "border-radius-end-start"},

  "border-image": { property: "border-image", composite: true, relatedProperties: ["border-image-outset", "border-image-repeat", "border-image-slice", "border-image-source", "border-image-width"]},
  "border-image-outset": { property: "border-image-outset"},
  "border-image-repeat": { property: "border-image-repeat"},
  "border-image-slice": { property: "border-image-slice"},
  "border-image-source": { property: "border-image-source"},
  "border-image-width": { property: "border-image-width"},

  "border-inline": { property: "border-inline", composite: true, relatedProperties: ["border-inline-width", "border-inline-style", "border-inline-color"]},
  "border-inline-color": { property: "border-inline-color"},
  "border-inline-end": { property: "border-inline-end", composite: true, relatedProperties: ["border-inline-end-width", "border-inline-end-style", "border-inline-end-color"]},
  "border-inline-end-color": { property: "border-inline-end-color"},
  "border-inline-end-style": { property: "border-inline-end-style"},
  "border-inline-end-width": { property: "border-inline-end-width"},
  "border-inline-start": { property: "border-inline-start", relatedProperties: ["border-inline-start-width", "border-inline-start-style", "border-inline-start-color"]},
  "border-inline-start-color": { property: "border-inline-start-color"},
  "border-inline-start-style": { property: "border-inline-start-style"},
  "border-inline-start-width": { property: "border-inline-start-width"},
  "border-inline-style": { property: "border-inline-style", composite: true, relatedProperties: ["border-inline-start-style", "border-inline-end-style"]},
  "border-inline-width": { property: "border-inline-width", composite: true, relatedProperties: ["border-inline-start-width", "border-inline-end-width"]},
  
  "border-spacing": {property: "border-spacing", composite: true, relatedProperties: ["border-spacing-x", "border-spacing-y"]},
  "border-collapse": {property: "border-collapse"},

  "box-shadow": {property: "box-shadow"},
  "box-sizing": {property: "box-sizing"},
  
  "box-decoration-break": {property: "box-decoration-break"},
  "break-after": {property: "break-after"},
  "break-before": {property: "break-before"},
  "break-inside": {property: "break-inside"},

  "block-size": { property: "block-size"},
  
  "color": {property: "color"},
  "cursor": {property: "cursor"},
  "clear": {property: "clear"},
  "caption-side" : {property: 'caption-side'},

  "clip": {property: "clip"},
  "clip-path" : {property: 'clip-path'},
  
  "columns": {property: "columns", composite: true, relatedProperties: ["column-width", "column-count"]},
  "column-count" : {property: 'column-count'},
  "column-fill" : {property: 'column-fill'},
  "column-rule" : {property: 'column-rule', composite: true, relatedProperties: ["column-rule-width", "column-rule-style", "column-rule-color"]},
  "column-rule-color" : {property: 'column-rule-color'},
  "column-rule-style" : {property: 'column-rule-style'},
  "column-rule-width" : {property: 'column-rule-width'},
  "column-span" : {property: 'column-span'},
  "column-width" : {property: 'column-width'},
  
  "counter-increment" : {property: 'counter-increment'},
  "counter-reset" : {property: 'counter-reset'},
  "counter-set" : {property: 'counter-set'},

  "caret": {property: "caret", composite: true, relatedProperties: ["caret-color", "caret-shape"]},
  "caret-color": {property: "caret-color"},
  "caret-shape": {property: "caret-shape"},
  "content": {property: "content"},

  "display": {property: "display"},
  "direction" : {property: 'direction'},

  "empty-cells" : {property: 'empty-cells'},

  "fill": {property: "fill"},
  "filter": {property: "filter"},

  "flex": {property: "flex", composite: true, relatedProperties: ["flex-grow", "flex-shrink", "flex-basis"]},
  "flex-basis": {property: "flex-basis"},
  "flex-shrink": {property: "flex-shrink"},
  "flex-grow": {property: "flex-grow"},
  "flex-direction": {property: "flex-direction"},
  "flex-wrap": {property: "flex-wrap"},
  "flex-flow": {property : "flex-flow", composite: true, relatedProperties: ["flex-direction" ,"flex-wrap"]},

  "float": {property: "float"},

  "font" : {property: 'font', composite: true, relatedProperties: ["font-style", "font-variant", "font-weight", "font-size", "line-height", "font-family"]},
  "font-weight": {property: "font-weight"},
  "font-family": {property: "font-family"},
  "font-size": {property: "font-size"},
  "font-size-adjust": {property: "font-size-adjust"},
  "font-stretch": {property: "font-stretch"},
  "font-variant": {property: "font-variant"},
  "font-variant-caps": {property: "font-variant-caps"},
  "font-variant-numeric": {property: "font-variant-numeric"},
  "font-style": {property: "font-style"},
  "font-feature-settings" : {property: 'font-feature-settings'},
  "font-kerning" : {property: 'font-kerning'},

  "gap": {property: "gap", composite: true, relatedProperties: ["row-gap", "column-gap"]},
  "row-gap": {property: "row-gap"},
  "column-gap": {property: "column-gap"},

  "grid-auto-columns": {property: "grid-auto-columns"},
  "grid-auto-rows": {property: "grid-auto-rows"},
  "grid-auto-flow": {property: "grid-auto-flow"},
  "grid-area": {property: "grid-area", composite: true, relatedProperties: ["grid-row-start", "grid-column-start", "grid-row-end", "grid-column-end"]},
  "grid-column": {property: "grid-column", composite: true, relatedProperties: ["grid-column-start", "grid-column-end"]},
  "grid-column-end": {property: "grid-column-end"},
  "grid-column-start": {property: "grid-column-start"},
  "grid-row": {property: "grid-row", composite: true, relatedProperties: ["grid-row-start", "grid-row-end"]},
  "grid-row-end": {property: "grid-row-end"},
  "grid-row-start": {property: "gridRowStart"},
  "grid-template-columns": {property: "gridTemplateColumns"},
  "grid-template-rows": {property: "gridTemplateRows"},
  "grid-template-areas": {property: "grid-template-areas"},
  "grid-template": {property: "grid-template", composite: true, relatedProperties: ["grid-template-columns", "grid-template-rows", "grid-template-areas"]},
  "grid": {property: "grid", composite: true, relatedProperties: ["grid-template-rows", "grid-template-columns", "grid-template-areas", "grid-auto-rows", "grid-auto-columns", "grid-auto-flow"]},
  "grid-column-gap" : {property: 'grid-column-gap'},
  "grid-gap" : {property: 'grid-gap', composite: true, relatedProperties: ["grid-row-gap", "grid-column-gap"]},
  "grid-row-gap" : {property: 'grid-row-gap'},

  "height": {property: "height"},

  "hyphenate-character" : {property: 'hyphenate-character'},
  "hyphens" : {property: 'hyphens'},

  "image-rendering" : {property: 'image-rendering'},
  "isolation" : {property: "isolation"},

  "inline-size" : {property: 'inline-size'},
  "inset-block" : {property: 'inset-block', composite: true, relatedProperties: ["inset-block-start", "inset-block-end"]},
  "inset-block-end" : {property: 'inset-block-end'},
  "inset-block-start" : {property: 'inset-block-start'},
  "inset-inline" : {property: 'inset-inline', composite: true, relatedProperties: ["inset-inline-start", "inset-inline-end"]},
  "inset-inline-end" : {property: 'inset-inline-end'},
  "inset-inline-start" : {property: 'inset-inline-start'},

  "justify-content": {property: "justify-content"},
  "justify-items": {property: "justify-items"},
  "justify-self": {property: "justify-self"},

  "inset": {property: "inset", composite: true, relatedProperties: ["top", "right", "bottom", "left"]},
  "top": {property: "top"},
  "right": {property: "right"},
  "bottom": {property: "bottom"},
  "left": {property: "left"},

  "letter-spacing": {property: "letter-spacing"},
  "line-height": {property: "line-height"},
  "line-break": {property: "line-break"},

  "list-style": {property: "list-style", composite: true, relatedProperties: ["list-style-type", "list-style-position", "list-style-image"]},
  "list-style-type": {property: "list-style-type"},
  "list-style-position": {property: "list-style-position"},
  "list-style-image": {property: "list-style-image"},
  
  "mask-image" : {property: 'mask-image'},
  "-webkit-mask-image" : {property: '-webkit-mask-image'},
  "mask-mode" : {property: 'mask-mode'},
  "mask-origin" : {property: 'mask-origin'},
  "-webkit-mask-origin" : {property: '-webkit-mask-origin'},
  "mask-position" : {property: 'mask-position'},
  "-webkit-mask-position" : {property: '-webkit-mask-position'},
  "mask-repeat" : {property: 'mask-repeat'},
  "-webkit-mask-repeat" : {property: '-webkit-mask-repeat'},
  "mask-size" : {property: 'mask-size'},
  "-webkit-mask-size" : {property: '-webkit-mask-size'},
  
  "max-height": {property: "max-height"},
  "max-width": {property: "max-width"},
  "min-height": {property: "min-height"},
  "min-width": {property: "min-width"},

  "max-block-size" : {property: 'max-block-size'},
  "max-inline-size" : {property: 'max-inline-size'},
  "min-block-size" : {property: 'min-block-size'},
  "min-inline-size" : {property: 'min-inline-size'},
  
  "margin": {property: "margin", composite: true, relatedProperties: ["margin-top", "margin-right", "margin-bottom", "margin-left"]},
  "margin-top": {property: "marginTop"},
  "margin-right": {property: "marginRight"},
  "margin-bottom": {property: "marginBottom"},
  "margin-left": {property: "marginLeft"},
  "margin-block" : {property: 'margin-block', composite: true, relatedProperties: ["margin-block-start", "margin-block-end"]},
  "margin-block-end" : {property: 'margin-block-end'},
  "margin-block-start" : {property: 'margin-block-start'},
  "margin-inline" : {property: 'margin-inline', composite: true, relatedProperties: ["margin-inline-start", "margin-inline-end"]},
  "margin-inline-end" : {property: 'margin-inline-end'},
  "margin-inline-start" : {property: 'margin-inline-start'},

  
  "mix-blend-mode": {property: "mix-blend-mode"},
  
  "object-position": {property: "object-position"},
  "object-fit": {property: "object-fit"},

  "offset" : {property: 'offset', composite: true, relatedProperties: ["offset-anchor", "offset-distance", "offset-path", "offset-rotate"]},
  "offset-anchor" : {property: 'offset-anchor'},
  "offset-distance" : {property: 'offset-distance'},
  "offset-path" : {property: 'offset-path'},
  "offset-rotate" : {property: 'offset-rotate'},

  "opacity": {property: "opacity"},
  "order": {property: "order"},
  "orphans" : {property: 'orphans'},
  
  "outline": {property: "outline", composite: true, relatedProperties: ["outline-style", "outline-width", "outline-color"]},
  "outline-offset": {property: "outline-offset"},
  "outline-width": {property: "outline-width"},
  "outline-style": {property: "outline-style"},
  "outline-color": {property: "outline-color"},
  
  "overflow": {property: "overflow"},
  "overflow-x": {property: "overflow-x"},
  "overflow-y": {property: "overflow-y"},
  "overflow-wrap": {property: "overflow-wrap"},
  "overflow-anchor" : {property: 'overflow-anchor'},

  "overscroll-behavior": {property: "overscroll-behavior", composite: true, relatedProperties: ["overscroll-behavior-x", "overscroll-behavior-y"]},
  "overscroll-behavior-x": {property: "overscroll-behavior-x"},
  "overscroll-behavior-y": {property: "overscroll-behavior-y"},
  "overscroll-behavior-block" : {property: 'overscroll-behavior-block'},
  "overscroll-behavior-inline" : {property: 'overscroll-behavior-inline'},

  "page-break-after" : {property: 'page-break-after'},
  "page-break-before" : {property: 'page-break-before'},
  "page-break-inside" : {property: 'page-break-inside'},

  "paint-order" : {property: 'paint-order'},
  "perspective" : {property: 'perspective'},
  "perspective-origin" : {property: 'perspective-origin'},
  
  "padding": {property: "padding", composite: true, relatedProperties: ["padding-top", "padding-right", "padding-bottom", "padding-left"]},
  "padding-top": {property: "padding-top"},
  "padding-right": {property: "padding-right"},
  "padding-bottom": {property: "padding-bottom"},
  "padding-left": {property: "padding-left"},
  "padding-block" : {property: 'padding-block', composite: true, relatedProperties: ["padding-block-start", "padding-block-end"]},
  "padding-block-end" : {property: 'padding-block-end'},
  "padding-block-start" : {property: 'padding-block-start'},
  "padding-inline" : {property: 'padding-inline', composite: true, relatedProperties: ["padding-inline-start", "padding-inline-end"]},
  "padding-inline-end" : {property: 'padding-inline-end'},
  "padding-inline-start" : {property: 'padding-inline-start'},

  "place-content": {property: "place-content"},
  "place-items": {property: "place-items"},
  "place-self": {property: "place-self"},
  
  "position": {property: "position"},
  "pointer-events": {property: "pointer-events"},

  "quotes" : {property: 'quotes'},
  
  "scale": {property: "scale"},

  "resize": {property: "resize"},
  "rotate": {property: "rotate"},

  "scrollbar-color" : {property: 'scrollbar-color'},

  "scroll-behavior": {property: "scroll-behavior"},
  "scroll-align": {property: "scroll-align"},
  "scroll-stop": {property: "scroll-stop"},

  "scroll-margin": {property: "scroll-margin", composite: true, relatedProperties: ["scroll-margin-top", "scroll-margin-right", "scroll-margin-bottom", "scroll-margin-left"]},
  "scroll-margin-top": {property: "scroll-margin-top"},
  "scroll-margin-right": {property: "scroll-margin-right"},
  "scroll-margin-bottom": {property: "scroll-margin-bottom"},
  "scroll-margin-left": {property: "scroll-margin-left"},
  "scroll-margin-inline": {property: "scroll-margin-inline", composite: true, relatedProperties: ["scroll-margin-inline-start", "scroll-margin-inline-end"]},
  "scroll-margin-inline-start": {property: "scroll-margin-inline-start"},
  "scroll-margin-inline-end": {property: "scroll-margin-inline-end"},
  "scroll-margin-block": {property: "scroll-margin-block", composite: true, relatedProperties: ["scroll-margin-block-start", "scroll-margin-block-end"]},
  "scroll-margin-block-start": {property: "scroll-margin-block-start"},
  "scroll-margin-block-end": {property: "scroll-margin-block-end"},

  "scroll-padding": {property: "scroll-padding", composite: true, relatedProperties: ["scroll-padding-top", "scroll-padding-right", "scroll-padding-bottom", "scroll-padding-left"]},
  "scroll-padding-top": {property: "scroll-padding-top"},
  "scroll-padding-right": {property: "scroll-padding-right"},
  "scroll-padding-bottom": {property: "scroll-padding-bottom"},
  "scroll-padding-left": {property: "scroll-padding-left"},
  "scroll-padding-inline": {property: "scroll-padding-inline", composite: true, relatedProperties: ["scroll-padding-inline-start", "scroll-padding-inline-end"]},
  "scroll-padding-inline-start": {property: "scroll-padding-inline-start"},
  "scroll-padding-inline-end": {property: "scroll-padding-inline-end"},
  "scroll-padding-block": {property: "scroll-padding-block", composite: true, relatedProperties: ["scroll-padding-block-start", "scroll-padding-block-end"]},
  "scroll-padding-block-start": {property: "scroll-padding-block-start"},
  "scroll-padding-block-end": {property: "scroll-padding-block-end"},

  "scroll-snap-align" : {property: 'scroll-snap-align'},
  "scroll-snap-stop" : {property: 'scroll-snap-stop'},
  "scroll-snap-type" : {property: 'scroll-snap-type'},
  
  "stroke": {property: "stroke"},
  "stroke-width": {property: "stroke-width"},
  "stroke-dashoffset": {property: "stroke-dashoffset"},
  "stroke-dasharray": {property: "stroke-dasharray"},
  "stroke-linecap": {property: "stroke-linecap"},
  "stroke-opacity": {property: "stroke-opacity"},
  "stroke-linejoin": {property: "stroke-linejoin"},
  "stroke-miterlimit": {property: "stroke-miterlimit"},
  "-webkit-text-stroke": {property: "-webkit-text-stroke"},
  "-webkit-text-stroke-color": {property: "-webkit-text-stroke-color"},
  "-webkit-text-stroke-width": {property: "-webkit-text-stroke-width"},
  
  "table-layout": {property: "table-layout"},
  "tab-size" : {property: 'tab-size'},
  
  "text-indent": {property: "text-indent"},
  "text-underline-offset": {property: "text-underline-offset"},
  "text-transform": {property: "text-transform"},
  "text-overflow": {property: "text-overflow"},
  "text-align": {property: "text-align"},
  "text-align-last" : {property: 'text-align-last'},
  "text-justify" : {property: 'text-justify'},
  "text-orientation" : {property: 'text-orientation'},
  "text-shadow" : {property: 'text-shadow'},
  "text-underline-position" : {property: 'text-underline-position'},
  
  "text-emphasis" : {property: 'text-emphasis', composite: true, relatedProperties: ["text-emphasis-style", "text-emphasis-color"]},
  "text-emphasis-color" : {property: 'text-emphasis-color'},
  "text-emphasis-position" : {property: 'text-emphasis-position'},
  "text-emphasis-style" : {property: 'text-emphasis-style'},

  "text-decoration": {property: "text-decoration", composite: true, relatedProperties: ["text-decoration-line", "text-text-decoration-style" ,"text-decoration-color", "text-decoration-thickness"]},
  "text-decoration-color": {property: "text-decoration-color"},
  "text-decoration-thickness": {property: "text-decoration-thickness"},
  "text-decoration-style": {property: "text-decoration-style"},
  "text-decoration-line": {property: "text-decoration-line"},
  "text-decoration-skip-ink": {property: "text-decoration-skip-ink"},
  "-moz-text-decoration-style": {property: "-moz-text-decoration-style"},
  "-moz-text-decoration-line": {property: "-moz-text-decoration-line"},
  "-moz-text-decoration-color": {property: "-moz-text-decoration-color"},

  "touch-action": {property: "touch-action"},
  
  "transition": {property: "transition", composite: true, relatedProperties: ["transition-property", "transition-delay", "transition-timing-function", "transition-delay"]},
  "transition-delay": {property: "transition-delay"},
  "transition-property": {property: "transition-property"},
  "transition-duration": {property: "transition-duration"},
  "transition-timing-function": {property: "transition-timing-function"},
  
  "transform": {property: "transform"},
  "transform-origin": {property: "transform-origin"},
  "transform-style": {property: "transform-style"},
  "transform-box": {property: "transform-box"},
  
  "translate": {property: "translate"},

  "user-select": {property: "user-select"},
  "unicode-bidi" : {property: 'unicode-bidi'},
  
  "vertical-align": {property: "vertical-align"},
  "visibility": {property: "visibility"},
  
  "width": {property: "width"},
  "will-change": {property: "will-change"},
  "white-space": {property: "white-space"},
  "white-space-collapse": {property: "white-space-collapse"},
  "widows" : {property: 'widows'},
  "writing-mode" : {property: 'writing-mode'},
  
  "word-break": {property: "word-break"},
  "word-spacing" : {property: 'word-spacing'},
  "word-wrap" : {property: 'word-wrap'},

  "z-index": {property: "z-index"},

  "-moz-tab-size": {property: "-moz-tab-size"},

  "-webkit-font-smoothing": {property: "-webkit-font-smoothing"},
  "-moz-osx-font-smoothing": {property: "-moz-osx-font-smoothing"},

  "-webkit-box-reflect" : {property: '-webkit-box-reflect'},
  "-webkit-backdrop-filter": {property: "-webkit-backdrop-filter"},
  "-webkit-filter": {property: "-webkit-filter"},
}